### ISSUE TITLE
The backup folder is empty, and now I'm left having to start from scratch -_-

### ISSUE THREAD

**Issue by nickcorona** [unix121/i3wm-themer#10]
You should take this down if you're not going to alert people that the project is deprecated.

**Comment by unix121** [comment]
Good evening, the backup folder is probably not empty, you just can't see the files because they are hidden. Use the 'ls -al' command inside the folder to see the files. Also as mentioned this is not even a finished project and it's recommended that you just pick what you want from the themes instead of just using the script until I find the time to work on it again.
