### ISSUE TITLE
Major bugs in Debian.

### ISSUE THREAD

**Issue by Seraph87** [unix121/i3wm-themer#107]
I switched from Arch to Debian recently, and i3wm-themer was my favorite way to get i3 looking really good really quick on Arch. Well, after trying to get it working on Debian this evening, I've found that there are a lot of bugs, and this is a 2 day old install. 

I had issues getting the theme to change. Others have had these issues before, refer to the "no module named yaml" and "cannot import name ABC" issues. After following what others had said, I at least got the theme running, but polybar was nowhere to be found, more on that in a bit. What was curious to me, was that while my config file had the windows key set as my mod key, my alt key was acting as the mod key instead. That had never happened on the Arch install.

Onto the polybar issue. Someone had this problem before me, and I followed their solution to it. What happened next was I got logged out of i3 completely, out to lightdm. Upon trying to log back in, I got a black screen for about 2 seconds, and then kicked back out to lightdm. I went back into my Xfce session to uninstall i3 and the themer completely, and reinstalled i3. I tried to log in, but I still had the black screen and getting kicked out issue. I went to an extreme measure and restored to a timeshift backup I made right before I even installed i3, and someway, somehow, the issue was still there.

I would LOVE to use the themer on my Debian install, but all of the bugs have rendered base i3 unusable on my machine. The only way I could have a chance to make it work again would be to completely reinstall Debian. I noticed that the other users I mentioned earlier were all Debian users as well. 

PLEASE look into working out the kinks for the Debian version. The Arch version is amazing and works so smoothly, I'd love to see it work that way on Debian!

**Comment by unix121** [comment]
Hello sir,

Yes I do agree that there are some major and minor issues depending on the Linux distribution that one uses. Personally (once I am running this project solo), I cannot always test every update on every possible distribution, so I always expect some bugs to occur here and there.

About the module issue, I have also faced it a few times and I believe it is mostly depended on the Python version. It gets a bit confusing sometimes with the versioning and the modules needed. I always hoped for this project to be distributed via PiPY in order to avoid those types of issues, but personally I don't have the time to spend that much on packaging.

On the Polybar issue, I haven't really looked into it that much so I cannot offer a complete solution.

Usability on every distribution would be like the optimal for this project, but sadly, the differences between some distributions make it impossible. As always I am always open to suggestions on such issues and always look carefully on PRs before merging them, so if you (or anyone) has any idea/suggestion/code on how to improve things, please don't be afraid to open an issue/PR.

**Comment by unix121** [comment]
One side note here, (not meant to be an excuse or anything), when I started this project I never expected so many people to find it useful, it was a tool that I created for my personal use that was supposed to work for the distro that I was running back then (Manjaro at the time).

My main focus for this project is always 1 or 2 major updates per year to fix known issues etc (that the max time I can spend on this project usually), that's why I rely so much on other people's contributions and any change, small or big is always welcome.

**Comment by cizordj** [comment]
@Seraph87 my [fork](https://github.com/cizordj/i3-themer) of i3wm-themer is focused on Debian mainly and has all the necessary dependencies built-in. Unfortunately, it is too different from the original project to make a pull request. Forgive me @unix121

**Comment by unix121** [comment]
Hello @cizordj , I checked your version, yes it's too different to even attempt to merge. But it seems to me that it can do the job for Debian users. If you wish, you can make a new PR on this project adding a link to your project at the bottom of the README.md. Maybe a new section `Similar Projects` or something if you want to.

**Comment by cizordj** [comment]
Alright, if you don't mind I will make this pull request soon.
