### ISSUE TITLE
Please convert every file in this to a jinja theme or similar.

### ISSUE THREAD

**Issue by cmpunches** [unix121/i3wm-themer#15]
Hello,

Avoiding the apparent design issues with interpolation checks, I might suggest that you instead move to using jinja templates or similar for all files and then doing a full file replacement during application of themes,after storing the last used theme in a backup folder automatically.  And then making the paths configurable in a config file for the tool itself.

This will give you much greater flexibility in each theme and will make themes almost universally applicable.  I would also do away completely with any interaction with .Xresources and .extend.X*.

I'd submit a pull request doing this myself but it would be a full rewrite, and I'll need to devote that time to unkinking all my config files now to get a usable desktop again.

**Comment by unix121** [comment]
Hello @cmpunches , I'd be glad to work on this if you could point me to the right direction here. Your idea seems great but there is one point that I'm not so into. The first version I even wrote did a full file replacement but I removed it because it would cause problems to some people for the simple reason that it would overwrite their keybindings/default programs etc. For personal use yeah it's great and way faster but for general use I'm not that sure. 

I'll check your idea once you submit it, if it works better be sure that it will get merged.

I've wanted to rework this project but I cannot still find the time once I'm extremely busy for the past few months, so your help is always appreciated. Also thank you for your honest critique.

**Comment by cmpunches** [comment]
For keybindings you could just have a separate template file included in
that theme's template where the user defines their keybindings, but really
they're applying a theme, this is not so important.  If they want custom
keybindings I think they should add them in after applying the theme.

There's no general use right now as it is.

On Mon, Jan 22, 2018 at 7:52 AM, Stavros Grigoriou <notifications@github.com

**Comment by unix121** [comment]
Well in that case do as you wish sir, your idea is good enough for me.

**Comment by unix121** [comment]
Hello sir,

The whole repository has been reworked, so I'm closing this issue for now. In case you meet any new issues then please open a new `Issue` thread that is more up-to-date.
