### ISSUE TITLE
about the lightdm bug

### ISSUE THREAD

**Issue by taotao7** [unix121/i3wm-themer#20]
- i use login management is lightdm 
- my linux releases is arch now i can't open the terminal on desktop and no wallpaper
- everything works fine in a non-graphical interface
- there is no way to shutdown my computer from the graphical interface

what should i do

**Comment by taotao7** [comment]
ok now i copy my /etc/i3/config file to there

**Comment by unix121** [comment]
Hi again,

My best guess is that you must edit <a href="https://github.com/unix121/i3wm-themer/blob/master/src/defaults/i3.template#L16">this line</a> and add your terminal emulator. The wallpaper sometimes happens because NItrogen doesn't restore the previous background (it's a known issue).

I guess you can launch Rofi, so you Rofi to access your terminal and edit your configs from there.

Generally it's a good idea to read my configs before you use them just in case you need to change something.

If the issue is resolved then close this issue.

**Comment by taotao7** [comment]
yeah thank u
