### ISSUE TITLE
i3 config file is not changing & polybar errors

### ISSUE THREAD

**Issue by failex234** [unix121/i3wm-themer#4]
I tried applying some themes but every time after your script applied these changes, my i3 Appearance + my i3 config haven't changed at all. If I try to run polybar I get this error: "error: The reference ${colors.color04_i3wmthemer} does not exist (no fallback set)". What can I do? My i3 config is located in .config/i3/config + a link from .i3/config to .config/i3/config.

**Comment by ve9u** [comment]
maybe because of typo at this line https://github.com/unix121/i3wm-themer/blob/master/scripts/i3wmthemer#L177

It should be config not conig, can you try same thing by replacing the line with below line.

 i3path=$HOME/.config/i3/config

I also had problem while running ` ./i3wmthemer -c`

**Comment by unix121** [comment]
Hello there, 

First of thanks for your feedback, I think that @ve9u is right, I'm going to fix that problem right now. If you still get the error after the fix, could you please post your dotfiles somewhere so that I have a complete image of what we are talking about? I will spend more time into the script, it's still under development so some errors might occure here and there. Also if you can post a copy of the output of the script after you run to apply a theme, that would be helpful.

@ve9u I'm going to add that change and add you into the list of contributors, thanks for contributing mate. :)

**Comment by unix121** [comment]
Also @failex234 make sure that those lines where copied at your polybar configuration file:
https://github.com/unix121/i3wm-themer/blob/master/templates/.config/polybar/config
If they are not then copy them manually at the right place (should be listed under the [color] tag).
