### ISSUE TITLE
Yaourt Automatically installed for Arch users

### ISSUE THREAD

**Issue by alopexc0de** [unix121/i3wm-themer#41]
Yaourt has not been in active development for a number of years now and is no longer recommended as it is not secure in the way that it builds packages from the AUR.

Instead of forcing this on Arch users (and not uninstalling it at the end of setup if it installed itself in the first place...), I would instead attempt to find an AUR helper from the [Arch WIKI](https://wiki.archlinux.org/index.php/AUR_helpers#Active) that is already installed and use that instead.

**Comment by unix121** [comment]
Hello sir,

Sorry for the late response. Hard days.

I think that this is a great recommendation! It was kinda overlooked by me, I still use `yaourt` but only because I was used to it from the good old days. First time I get a chance I will research all the available options and try to figure out what people prefer (or even have multiple options, idk) and start working on it. As always any help is welcome!

**Comment by ooaj** [comment]
yay or trizen should be a solid choice these days.
