### ISSUE TITLE
Errors running i3wm in Ubuntu 16.04 after aplying install_ubuntu.sh script

### ISSUE THREAD

**Issue by logoff** [unix121/i3wm-themer#44]
I run the script `install_ubuntu.sh` in my machine with Ubuntu 16.04. Everything seems to be OK after running the script, with no apparent errors. But when I choose to log in with my user using i3, it returns back to log-in screen.

I attach `~/.xsession-errors` generated file [xsession-errors.zip](https://github.com/unix121/i3wm-themer/files/2340138/xsession-errors.zip).

It seems a weird error of `libxcb-cursor`.

Do you know how to cope with this crash?

**Comment by orestisf1993** [comment]
Try `../configure --prefix=/usr --sysconfdir=/etc --disable-sanitizers`.

It's not a great idea to run i3 as your daily driver with sanitizers enabled. Memory used by i3bar & i3 is going to increase quite a bit.

It would be interesting to figure out why the error happens with sanitizers though, it doesn't make any sense to me.

**Comment by logoff** [comment]
@orestisf1993 where should I use this line? In the script there is only one place where a configure is applied ([here](https://github.com/unix121/i3wm-themer/blob/master/install_ubuntu.sh#L38)) to `i3-gaps`.

**Comment by unix121** [comment]
Hello guys,

Sorry for the late response, I've been really busy this week.

That error seems weird to me and I can't reproduce it, so a bit more info on how to reproduce this error would be great. Blind-shooting possible solutions is not the greatest thing to do once it can seriously break your system, so if you could and are willing to do so, please provide some steps on how I (or anyone who wants to help) can reproduce this.

In any case I would strongly recommend that you keep ricing your desktop in the 'oldschool' way or use another tool like for example [pywal](https://github.com/dylanaraps/pywal) as an alternative (or any other alternative since they are all great).

I'm going to come back to this project soon, try to fix all the known issues and add more functionality and ability to dynamically import/export themes and maybe integrations with other great applications. But until then there are not many things that can be done. 

The project is kinda in a `pause` because of the huge workload that I have, so without any external help it's going to take some time to get it started again. So as always any contribution, code, help with the comments, even bug-finding like this one is always welcome.

**Comment by orestisf1993** [comment]
@logoff yes, that's the line

**Comment by logoff** [comment]
@orestisf1993 the change solved the loop in lg-in screen, great!! Now I'm able to log-in. It is not running perfectly, but it boots :smile: I have some issues with multiple monitors and other minor things. I will try to debug one by one. Anyway it seems that the original problem is there, we don't know where...

Thank you for your effort!

@unix121 Thank you for the reply. I appreciate your effort in this repo :wink: I will try to play a bit with i3 and all the tools you added in your setup. Hope you have time to improve this and other fancy tools.
